### ISSUE TITLE
spy on midi out ports

### ISSUE THREAD

**Issue by JOJ0** [gbevin/ReceiveMIDI#3]
Hi, 
first of all: thank you for saving me ages of coding time, I was missing a unix type commandline midi monitor utility and was thinking about creating one myself in python or something. Fortunately your tool already exists and is almost exactely what I was looking for! It probably would have taken me years to complete haha ;-)

One thing that I am missing is a feature that I know from snoize MIDI Monitor. You can monitor what goes into an actual midi output port. You probably know MIDI Monitor, it's called "spy on output to destinations" in the gui.

For instance sometimes I work with midi manipulator tools like "MIDIpipe". I would like to see what goes into midi pipe from my daw (Output Port: MidiPipe Input 1), and see what comes out after midi pipe (Input Port: MidiPipe Output 1). 

Or another usecase was when I wanted to proof that a cheap china usb midi adapter does not transmit all midi data, it looses some ;-)

Is there any way this would be possible with receivemidi, maybe in combination with sendmidi or something?
Hope this all makes sense. 

Thanks again!
all the best 
Jojo

**Comment by gbevin** [comment]
Hi Jojo,

Thanks for the kind words. I don't intend on supporting the "spy on output destinations" feature of MIDI Monitor, mainly because I want to keep the ReceiveMIDI and SendMIDI tools completely cross-platform and super easy to use and install. The spy feature requires the installation of a special macOS MIDI driver. The sources for this are available though: https://github.com/krevis/MIDIApps/tree/master/Frameworks/SnoizeMIDISpy

Maybe this could bootstrap your own personal efforts to combine this with ReceiveMIDI.

Take care,

Geert
